# Generated by Django 3.2.3 on 2021-05-14 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contatos', '0002_alter_contact_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
